name: "Automatic PR comment: Try this PR!"

on:
  push:
  workflow_dispatch:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const r = require("./hello.js")
            console.log(r)
            console.log(r.f)
  
