name: "Automatic PR comment: Try this PR!"

on:
  pull_request:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
              ## Try this Pull Request!
              Open Julia, and type:
              \`\`\`
              julia> ]
              (@v1.6) pkg> activate --temp
              (@v1.6) pkg> add ${context.payload.pull_request.head.repo.html_url}#${context.payload.pull_request.head.ref}
              (@v1.6) pkg> # press backspace/delete to go back
              julia> using ${context.repository.name.replace(/\.jl$/,"")}
              \`\`\`
              `
            })
